### ISSUE TITLE
Error 422

### ISSUE THREAD

**Issue by dm94** [meta-dog/meta-bones#8]
![image](https://user-images.githubusercontent.com/7419213/193019373-d76db872-1f88-4a9f-955d-2237d723297f.png)

**Comment by davidciglesias** [comment]
Hi @dm94, thanks for the issue  😄

The 422 error means that the link has been deemed invalid by the verification process and is therefore blacklisted, so you cannot add it to the queue (I recently changed the message that appears so it's a bit more descriptive).

In this case in particular, your referral link would be:

https://www.oculus.com/appreferrals/Dm94Dani/2448060205267927

If you try to open it while logged in, you'll see that Meta states that it is erroneous.

(However, if you open it via incognito it shows as a Beat Saber discount, right until you log in).

Alas, in this case it means that you haven't created the Referral from the Oculus App first. Please try doing that and then let me know so I can remove it from the blacklist. Thanks! 😄

**Comment by dm94** [comment]
My mistake, now I create the links in the mobile app and send them again.

**Comment by davidciglesias** [comment]
No problem! It it helps, here are the links that were added to the blacklist (I've removed them now so you can try again after you generate the links)

Beat Saber (Quest)
Creed: Rise to Glory (Quest)
Virtual Desktop (Quest)
Blade & Sorcery: Nomad (Quest)
Job Simulator (Quest)
Contractors (Quest)
Population One (Quest)
